# Generated by Django 4.2.4 on 2023-08-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
